# Generated by Django 3.2 on 2021-10-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
